name: pangolin

on: [push, pull_request]

jobs:
  run_pangolin_test:
    name: Pangolin test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cov-lineages/pangolin
          ref: v2.0.8
          path: pangolin
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: pangolin/environment.yml
          activate-environment: pangolin
          channels: conda-forge,bioconda,defaults
          mamba-version: "*"
      - name: Install pangolin
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE/pangolin
          pip install -e .
      - name: Check pangolin version
        shell: bash -l {0}
        run: pangolin --version
      - name: Run pangolin with test data
        shell: bash -l {0}
        run: pangolin $GITHUB_WORKSPACE/pangolin/pangolin/test/test_seqs.fasta 2>&1 | tee pangolin.log
# add more tests here